### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by webmaster33** [tiborbaksa/vlc-mediaklikk-video#1]
Using vlc-3.0.0-20171129-0442-git-win64.exe release.
https://nightlies.videolan.org/build/win64/vlc-3.0.0-20171129-0442/vlc-3.0.0-20171129-0442-git-win64.exe

I tried to copy mediaklikk-video.lua to C:\Program Files\VideoLAN\VLC\lua\playlist\ in 
Windows 7 Pro.
Restarted VLC.
But I don't find mediaklikk in any menu.
Where should I see it?

**Comment by tiborbaksa** [comment]
Hi @webmaster33, sorry for the late reply. You need to open an URL in VLC from one of Mediaklikk's sites (see the README for the list of supported sites). For example, to watch M4 Sport, open https://www.mediaklikk.hu/m4-elo in VLC like you would open any other stream URL. This is similar to how VLC can play videos from YouTube an other media sites.
