### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by eisengrau** [tiborbaksa/vlc-mediaklikk-video#2]
Hello Tibor,

Sorry for being such a n00b, and bothering with a even n000ber question, but how does this exacly work? I have copied the lua script in the specified directory in Windows, using the most recent VLC (3.0.4), but what should I do next to open the stream? The playlist is empty, and If I open the stream link directly, ex. https://www.mediaklikk.hu/duna-elo, the play does not want to play it? Does Mediaklikk changed something with their streaming solution or am I missing something?

Thank you,
Loránd

**Comment by tiborbaksa** [comment]
Hi @andlor, I think you were on the right path, it should work just by opening the link in VLC. It works for me at the moment, I don't think MediaKlikk changed anything. It would be helpful if you could include the [debug messages](https://stackoverflow.com/questions/4303017/how-to-get-vlc-logs) when trying to open one of the streams. When working properly, it should look something like this:
```
main debug: processing request item: duna-elo, node: Playlist, skip: 0
...
lua debug: Trying Lua scripts in C:\Users\tiborbaksa\AppData\Roaming\vlc\lua\playlist
lua debug: Trying Lua playlist script C:\Users\tiborbaksa\AppData\Roaming\vlc\lua\playlist\mediaklikk-video.lua
lua debug: Lua playlist script C:\Users\tiborbaksa\AppData\Roaming\vlc\lua\playlist\mediaklikk-video.lua's probe() function was successful
...
lua debug: mediaklikk-video: Number of players: 1
lua debug: mediaklikk-video: Loading player: https://player.mediaklikk.hu/playernew/player.php?video=dunalive
...
lua debug: Path: https://c202-node61-cdn.connectmedia.hu/1002/901de90a6f9fb6a0f2cb2d8d8a15235b/5bc79430/index.m3u8?v=5i
lua debug: Title: Duna
lua debug: ArtURL: http://mediaklikk.cms.mtv.hu/wp-content/uploads/sites/4/2017/11/mediaklikk_fb_default.jpg
...
main debug: processing request item: index.m3u8?v=5i, node: Playlist, skip: 0
...
```

**Comment by eisengrau** [comment]
Hi Tibor,

Sorry for the late reply. It seems that for some reason it won't even load your script:

> main debug: processing request item: (null), node: Playlist, skip: 0
> main debug: resyncing on (null)
> main debug: (null) is at 0
> main debug: starting playback of new item
> main debug: resyncing on (null)
> main debug: (null) is at 0
> main debug: creating new input thread
> main debug: Creating an input for '(null)'
> main debug: requesting art for new input thread
> main debug: using timeshift granularity of 50 MiB
> main debug: using timeshift path: C:\Users\lomo01\AppData\Local\Temp
> main debug: `https://www.mediaklikk.hu/m1-elo/' gives access `https' demux `any' path `www.mediaklikk.hu/m1-elo/'
> main debug: creating demux: access='https' demux='any' location='www.mediaklikk.hu/m1-elo/' file='\\www.mediaklikk.hu\m1-elo\'
> main debug: looking for access_demux module matching "https": 15 candidates
> main debug: no access_demux modules matched
> main debug: creating access: https://www.mediaklikk.hu/m1-elo/
> main debug: (path: \\www.mediaklikk.hu\m1-elo\)
> main debug: looking for access module matching "https": 26 candidates
> main debug: looking for meta fetcher module matching "any": 1 candidates
> main debug: looking for tls client module matching "any": 1 candidates
> gnutls debug: using GnuTLS version 3.5.18
> lua debug: Trying Lua scripts in C:\Users\lomo01\AppData\Roaming\vlc\lua\meta\fetcher
> lua debug: Trying Lua scripts in C:\Program Files\VideoLAN\VLC\lua\meta\fetcher
> main debug: no meta fetcher modules matched
> main debug: looking for art finder module matching "any": 2 candidates
> lua debug: Trying Lua scripts in C:\Users\lomo01\AppData\Roaming\vlc\lua\meta\art
> lua debug: Trying Lua scripts in C:\Program Files\VideoLAN\VLC\lua\meta\art
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\meta\art\00_musicbrainz.luac
> qt debug: IM: Setting an input
> lua debug: skipping script (unmatched scope) C:\Program Files\VideoLAN\VLC\lua\meta\art\00_musicbrainz.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\meta\art\01_googleimage.luac
> lua debug: skipping script (unmatched scope) C:\Program Files\VideoLAN\VLC\lua\meta\art\01_googleimage.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\meta\art\02_frenchtv.luac
> lua debug: skipping script (unmatched scope) C:\Program Files\VideoLAN\VLC\lua\meta\art\02_frenchtv.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\meta\art\03_lastfm.luac
> lua debug: skipping script (unmatched scope) C:\Program Files\VideoLAN\VLC\lua\meta\art\03_lastfm.luac
> main debug: no art finder modules matched
> gnutls debug: loaded 99 trusted CAs from system
> main debug: using tls client module "gnutls"
> main debug: resolving www.mediaklikk.hu ...
> gnutls debug: TLS handshake: Resource temporarily unavailable, try again.
> gnutls debug: TLS handshake: Resource temporarily unavailable, try again.
> gnutls debug: TLS handshake: Success.
> gnutls debug: - safe renegotiation (RFC5746) enabled
> gnutls debug: - false start (RFC7918) enabled
> http debug: outgoing request: GET /m1-elo/ HTTP/1.1 Host: www.mediaklikk.hu Accept: */* Accept-Language: en_GB User-Agent: VLC/3.0.4 LibVLC/3.0.4 Cookie: SERVERID=mtvacookieA Range: bytes=0- 
> http debug: incoming response: HTTP/1.1 200 OK Content-Type: text/html Vary: Accept-Encoding ETag: W/"5bd1c745-13d33" X-Cacheable: YES Transfer-Encoding: chunked Date: Thu, 25 Oct 2018 13:41:25 GMT Age: 85 X-Cache: cached X-UA-Compatible: IE=edge,chrome=1 
> main debug: using access module "access"
> main debug: looking for stream_filter module matching "prefetch,cache_block": 24 candidates
> prefetch debug: using 16777216 bytes buffer, 16384 bytes read
> main debug: using stream_filter module "prefetch"
> main debug: looking for stream_filter module matching "any": 24 candidates
> lua debug: Trying Lua scripts in C:\Users\lomo01\AppData\Roaming\vlc\lua\playlist
> lua debug: Trying Lua playlist script C:\Users\lomo01\AppData\Roaming\vlc\lua\playlist\mediaklikk-video.lua
> lua warning: error loading script C:\Users\lomo01\AppData\Roaming\vlc\lua\playlist\mediaklikk-video.lua: C:\Users\lomo01\AppData\Roaming\vlc\lua\playlist\mediaklikk-video.lua:9: unexpected symbol near '
> lua debug: Trying Lua scripts in C:\Program Files\VideoLAN\VLC\lua\playlist
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\anevia_streams.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\anevia_xml.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\appletrailers.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\bbc_co_uk.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\cue.luac
> prefetch debug: end of stream
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\dailymotion.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\jamendo.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\koreus.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\liveleak.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\newgrounds.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\rockbox_fm_presets.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\soundcloud.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\twitch.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\vimeo.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\vocaroo.luac
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\playlist\youtube.luac
> main debug: no stream_filter modules matched
> main debug: looking for stream_directory module matching "any": 1 candidates
> main debug: no stream_directory modules matched
> main debug: attachment of directory-extractor failed for https://www.mediaklikk.hu/m1-elo/
> main debug: looking for stream_filter module matching "record": 24 candidates
> main debug: using stream_filter module "record"
> main debug: creating demux: access='https' demux='any' location='www.mediaklikk.hu/m1-elo/' file='\\www.mediaklikk.hu\m1-elo\'
> main debug: looking for demux module matching "any": 55 candidates
> main debug: looking for xml reader module matching "any": 1 candidates
> main debug: using xml reader module "xml"
> ts debug: TS module discarded (lost sync)
> mod debug: MOD validation failed (ext=hu\m1-elo\)
> webvtt debug: subtitle demux discarded
> avcodec debug: trying url: \\www.mediaklikk.hu\m1-elo\
> avcodec debug: CPU flags: 0x000fd3db
> avcodec debug: couldn't guess format
> vobsub debug: this doesn't seem to be a vobsub file
> ps warning: this does not look like an MPEG PS stream, continuing anyway
> main debug: using demux module "ps"
> main debug: looking for meta reader module matching "any": 2 candidates
> lua debug: Trying Lua scripts in C:\Users\lomo01\AppData\Roaming\vlc\lua\meta\reader
> lua debug: Trying Lua scripts in C:\Program Files\VideoLAN\VLC\lua\meta\reader
> lua debug: Trying Lua playlist script C:\Program Files\VideoLAN\VLC\lua\meta\reader\filename.luac
> main debug: no meta reader modules matched
> main debug: `https://www.mediaklikk.hu/m1-elo/' successfully opened
> ps warning: garbage at input from 509, trying to resync...
> main debug: EOF reached
> main debug: removing module "ps"
> main debug: removing module "record"
> main debug: removing module "prefetch"
> main debug: removing module "access"
> main debug: dead input
> main debug: changing item without a request (current 0/1)
> main debug: nothing to play
> qt debug: IM: Deleting the input

Can you get something out if this to check what could be the issue?

**Comment by tiborbaksa** [comment]
The key is this line:
```
lua warning: error loading script C:\Users\lomo01\AppData\Roaming\vlc\lua\playlist\mediaklikk-video.lua: C:\Users\lomo01\AppData\Roaming\vlc\lua\playlist\mediaklikk-video.lua:9: unexpected symbol near '
```

Could you check if the file has the expected content? I think it might be corrupt.

**Comment by eisengrau** [comment]
Hi Tibor,

Sorry for the late reply again. Just so you know, you were right, the file was indeed corrupted. It is working, as advertised, thank you!

Regards,
Loránd
